apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData: 
  production.yml: |
    server: 
      port: 5505 
      host: localhost
    kafka:
      broker:
      - pkc-example.ap-south-2.aws.confluent.cloud:9092
      ssl: true
      sasl:
        username: YOUR_KAFKA_USERNAME
        password: YOUR_KAFKA_PASSWORD
    mail:
      host: smtp.example.com
      port: 465
      auth:
        user: your-email@example.com
        pass: your-email-password
      from: '"Notification" <your-email@example.com>'
    frontend:
      clientUI: https://example.com
