apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
stringData:
  production.yaml: |
    server: 
      port: 5502
      host: localhost
    database:
      url: mongodb+srv://username:password@cluster.mongodb.net/catalog_db?appName=cluster
    auth:
      jwksUri: http://auth-service:5501/.well-known/jwks.json
    s3:
      accessKeyId: YOUR_AWS_ACCESS_KEY_ID
      secretAccessKey: YOUR_AWS_SECRET_ACCESS_KEY
      region: ap-south-1
      bucket: your-bucket-name
    kafka:
      broker:
      - pkc-example.ap-south-2.aws.confluent.cloud:9092
      ssl: true
      sasl:
        username: YOUR_KAFKA_USERNAME
        password: YOUR_KAFKA_PASSWORD
    frontend:
      clientUI: https://example.com
      adminUI: https://admin.example.com
