apiVersion: v1
kind: Secret
metadata:
  name: order-secret
stringData: 
  production.yml: |
    server: 
      port: 5503
      host: localhost
    database:
      url: mongodb+srv://username:password@cluster.mongodb.net/order_db?appName=cluster
    auth:
      jwksUri: http://auth-service:5501/.well-known/jwks.json
    kafka:
      broker:
      - pkc-example.ap-south-2.aws.confluent.cloud:9092
      ssl: true
      sasl:
        username: YOUR_KAFKA_USERNAME
        password: YOUR_KAFKA_PASSWORD
    frontend:
      clientUI: https://example.com
      adminUI: https://admin.example.com
    stripe:
      secretKey: sk_test_YOUR_STRIPE_SECRET_KEY
