apiVersion: v1
kind: Secret
metadata:
  name: ws-secret
stringData: 
  production.yml: |
    server: 
      port: 5504 
      host: localhost
    kafka:
      broker:
      - pkc-example.ap-south-2.aws.confluent.cloud:9092
      ssl: true
      sasl:
        username: YOUR_KAFKA_USERNAME
        password: YOUR_KAFKA_PASSWORD
    frontend:
      clientUI: https://example.com
      adminUI: https://admin.example.com
