apiVersion: v1
kind: Secret
metadata:
  name: auth-env-secret
type: Opaque
stringData:
  .env.production: |
    PORT=5501
    NODE_ENV=production
    DB_HOST=localhost
    DB_PORT=5432
    DB_USERNAME=postgres
    DB_PASSWORD=your_password_here
    DB_NAME=postgres
    REFRESH_TOKEN_SECRET=your_refresh_token_secret_here
    JWKS_URI=http://localhost:5501/.well-known/jwks.json
    MAIN_DOMAIN=example.com
    CLIENT_UI_DOMAIN=https://www.example.com
    ADMIN_UI_DOMAIN=https://admin.example.com
